services:
  - type: web
    name: lynn-music
    env: python
    buildCommand: "curl -fsSL https://deno.land/install.sh | sh && pip install -U -r requirements.txt"
    startCommand: "export PATH=\"$HOME/.deno/bin:$PATH\" && python api_server.py"
    envVars:
      - key: PORT
        value: 10000
    plan: free
